dasch-swiss/dsp-ui-lib

projects/knora-ui/src/lib/viewer/values/base-value.component.ts
projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts
projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts

Moved `if (this.valueFormControl !== undefined && this.commentFormControl !== undefined)` from `ngOnChanges(changes: SimpleChanges): void` within each ValueComponent class to the beginning of `resetFormControl(): void` in the BaseValueComponent class in order to reduce duplication, see https://github.com/dasch-swiss/knora-ui-ng-lib/blob/481cf89db7bd42abba10328467e2c80f88ee1999/projects/knora-ui/src/lib/viewer/values/base-value.component.ts#L80-L103
Also moved the code from each `ngOnDestroy()` method to a new method in the BaseValueComponent class, see https://github.com/dasch-swiss/knora-ui-ng-lib/blob/481cf89db7bd42abba10328467e2c80f88ee1999/projects/knora-ui/src/lib/viewer/values/base-value.component.ts#L108-L112
so that we only need to call the function in the `ngOnDestroy()` method, …

feature (value): moved some shared logic to the component base class

---

.github/workflows/nodejs.yml
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts

I think I can come up with an alternative to using `inject` in an `it`.
Turns out that `KnoraApiCnnection` can be mocked with a simple object that defines spies for the methods that are actually called by the testes code.

Mock KnoraApiConnection in Tests

---

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/knora-ui/src/lib/viewer/values/custom-regex.ts
projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html
projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
projects/knora-ui/src/lib/viewer/viewer.module.ts
src/app/app.component.ts

Uri Value Component

---

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.scss
projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
projects/knora-ui/src/lib/viewer/viewer.module.ts
src/app/app.component.ts

closes #9 
Used checkbox instead of slide toggle because we should use a checkbox in case of a settings confirmation - which the most common case in Knora projects(see [this article](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8))

Boolean value component

---

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html
projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.scss
projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
projects/knora-ui/src/lib/viewer/viewer.module.ts
src/app/app.component.html
src/app/app.component.ts

_to do:_
**display:**
**edit:**
**test**
closes #14

Link value component

---

projects/knora-ui/ng-package.json
projects/knora-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts

It resolves the following warnings during the project build:
closes #49 
YouTrack issue: https://dasch.myjetbrains.com/youtrack/issue/DSP-51

Fix warnings during the "Bundling to UMD"

---

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/knora-ui/src/lib/viewer/values/list-value/list-display/list-display.component.html
projects/knora-ui/src/lib/viewer/values/list-value/list-display/list-display.component.ts
projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html
projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.scss
projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts
projects/knora-ui/src/lib/viewer/values/list-value/subList-value/sublist-value.component.html
projects/knora-ui/src/lib/viewer/values/list-value/subList-value/sublist-value.component.spec.ts
projects/knora-ui/src/lib/viewer/values/list-value/subList-value/sublist-value.component.ts
projects/knora-ui/src/lib/viewer/viewer.module.ts
src/app/app.component.ts

To display the value:
To edit the value:
test:
closes #15

List Value Component

---

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.scss
projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.html

The property label is displayed twice. 
It has been removed from property-view component (for now).
See [YouTrack issue 149](https://dasch.myjetbrains.com/youtrack/issue/DSP-149)

Clean up prop label

---

.github/workflows/main.yml
README.md
package-lock.json
package.json
projects/dsp-ui/README.md
projects/dsp-ui/package.json

After merging this PR, we'll create a new release v1.0.0-rc.1 which publishes the first @dasch-swiss/dsp-ui package to npm.

Prerelease v1.0.0-rc.1

---

projects/dsp-ui/ng-package.json
projects/dsp-ui/src/lib/action/components/progress-indicator/progress-indicator.component.spec.ts
src/app/action-playground/action-playground.component.spec.ts

https://dasch.myjetbrains.com/youtrack/issue/DSP-333

FIX: Action Module Playground & Components Missing Imports

---

projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.spec.ts
projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
src/app/action-playground/action-playground.component.html
src/app/action-playground/action-playground.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-337

Refactor Sort Button

---

projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-389

FIX: display-edit dev build errors

---

.github/workflows/main.yml
README.md
package-lock.json
package.json
projects/dsp-ui/LICENSE
projects/dsp-ui/README.md
projects/dsp-ui/package.json

This PR contains:
* Latest version of DSP-JS-LIB 1.0.0-rc.3
* Update README with link to DSP Release Compatibility Matrix and better title
* Update README with more badges to npm package
* Update description and information in package.json
* Improvement in Github Actions workflow config: Add tag `rc` in publish to npm process in case of prerelease. Otherwise publish without specific tag. The tag will make a difference in package version name as `latest` or as `prerelease`. 
For the review or after merging this PR, you should run `npm install` to grab the updated version of DSP-JS-LIB from npm!

Use latest rc of dsp-js and other improvements

---

e2e/protractor.conf.js
e2e/src/app.e2e-spec.ts
e2e/src/app.po.ts
projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.html
src/app/advanced-search-playground/advanced-search-playground.component.html
src/app/advanced-search-playground/advanced-search-playground.component.spec.ts
src/app/advanced-search-playground/advanced-search-playground.component.ts

resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-457
The E2E tests for the advanced search failed from time to time because async operations were no taken into account properly. For example, when an ontology has been selected, the UI has to get the ontology or ontologies from Knora. This could take some time. Unfortunately, the Harnesses in E2E tests [do not implement the necessary functionality yet](https://github.com/angular/components/issues/18375). 
As a solution, I use `browser.ExpectedConditions`: information fetched from Knora is expected to be displayed in the GUI within a defined time limit. Once the condition is met, the tests continues and further assertions can be checked safely.

Flaky E2E Tests

---

projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts

Temporary "fix" to hide the add button for an XML text property as long as there is no value component for it

FIX: hide the add button for an XML text property

---

e2e/src/app.e2e-spec.ts
projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts
projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-550
uses dsp-js 1.0.0.rc10

FIX: Delete Value UI Bug

---

projects/dsp-ui/src/assets/style/_viewer.scss
projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html
projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.scss
projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html
projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.scss
projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html
projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.scss
projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss

resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-587
This PR substitutes `<div>` and `<p>` elements for `<span>` elements in read-mode.
This should give users of the value components more flexibility when using them in an app.
For some components (date, timestamp, interval), I added some component specific CSS. I added general instructions for the `rm-value` class in the viewer's CSS since it is applied to all value components. 
However, I am still not sure how easy it would be to overwrite the styles provided by a lib on the app level.
Consider the following example from BEOL:
Because of _viewer.scss:
```css
.read-mode-view {
font: 400 15px/24px sans-serif;
.rm-value {
display: block;
}
}
```
there is some extra space for the date value. But it is needed because otherwise the …

Viewer: Use span Elements instead of div and p in Read Mode

---

projects/dsp-ui/src/lib/action/components/message/message.component.scss

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-636
uses js-lib rc.11

Message Component Css

---

projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-649
uses dsp-js rc.11 and dsp-api rc.15

Hide Geometry Property

---

projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-653
uses dsp-js rc.11 and dsp-api rc.15

Default Boolean Value

---

projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-651
uses dsp-js rc.11 and dsp-api rc.15

Geoname Value Styling

---

projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts

resolves [DSP-777](https://dasch.myjetbrains.com/youtrack/issue/DSP-777)

DSP-777 Show message on all server errors in login component

---

projects/dsp-ui/src/assets/style/_viewer.scss
projects/dsp-ui/src/assets/style/dsp-ui.scss
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.ts
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.html
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.scss
projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.ts
projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts

closes https://dasch.myjetbrains.com/youtrack/issue/DSP-638

Value Deletion Comment

---

projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.html
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
projects/dsp-ui/src/lib/viewer/values/base-value.component.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
src/config/config.dev.json
src/config/config.prod.json

resolves [DSP-682](https://dasch.myjetbrains.com/youtrack/issue/DSP-682)
`ValueTypeService.isReadOnly` has a a second required param now: `isReadOnly(valueTypeOrClass: string, value: ReadValue): boolean`

Integrate Ckeditor into Property View

---

projects/dsp-ui/src/lib/action/components/login-form/login-form.component.html
projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts
projects/dsp-ui/src/lib/action/components/message/message.component.html
projects/dsp-ui/src/lib/action/components/message/message.component.scss
projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts
projects/dsp-ui/src/lib/action/components/message/message.component.ts
projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.html
projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
projects/dsp-ui/src/lib/search/search.module.ts
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
src/app/action-playground/action-playground.component.html

resolves [DSP-779](https://dasch.myjetbrains.com/youtrack/issue/DSP-779)
For the reviewers:
- Open <http://localhost:4200/action> to see the the message component in action.
- Turn off the whole knora-stack (= server error 503) or only the database `knora-api_db_1` (= server error 500)
- Open <http://localhost:4200/viewer> to see the server error message 503 or 500
- Open <http://localhost:4200/search> and do a fulltext search or an expert search to see the server errors

DSP-779 Display error messages directly and not only in console

---

projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html

resolves [DSP-806](https://dasch.myjetbrains.com/youtrack/issue/DSP-806)

DSP-806 - Add the attribute 'rel' to uri and geoname value component template

---

projects/dsp-ui/src/lib/viewer/index.ts
projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/value.service.ts
projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts

resolves [DSP-759](https://dasch.myjetbrains.com/youtrack/issue/DSP-759)
Note that this PR renames `ValueTypeService` to `ValueService`.

DSP-759 Check if a Given Date Can Be Edited

---

projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html
projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
src/app/viewer-playground/viewer-playground.component.html
src/app/viewer-playground/viewer-playground.component.ts

resolves DSP-784
How to test this in the playground:
- add a standoff link to the text value on the modify page:
- from the "Viewer Module" tab you can now hover over or click standoff links (test) and links (Sierra) and get some console logs

Propagate Click Event to Res Viewer Comp.

---

projects/dsp-ui/design-documentation.md
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
src/app/modify/modify.component.html
src/app/modify/modify.component.ts

resolves DSP-1002
When adding an internal link to a text value, Knora creates a corresponding standoff link value.
When clicking on or hovering over a standoff link, this information can be used to emit the `ReadLinkValue`. Since this requires access to the standoff link value from the text value, `@Input() propArray: PropertyInfoValues[];` was added to `DisplayEditComponent`.

Update standoff link value

---

projects/dsp-ui/src/lib/viewer/services/value-operation-event.service.ts

This PRs adds the missing decorator to `ValueOperationEventService`.
https://angular.io/api/core/Injectable#usage-notes:
> Marking a class with @Injectable ensures that the compiler will generate the necessary metadata to create the class's dependencies when the class is injected.

Add missing decorator to ValueOperationEventService

---

projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/value.service.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts

resolves DSP-974 and DSP-1043
`ValueService.isReadOnly` has an additional third argument now: `propertyDef: ResourcePropertyDefinition`.
I added the flag "breaking" because this method could be used directly by the app.

Determine from ontology if a property is read-only

---

projects/dsp-ui/src/assets/style/_viewer.scss
projects/dsp-ui/src/assets/style/dsp-ui.scss
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.scss
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts

resolves DSP-788
Reapplies changes from #212 which was merged by accident.

CKEditor Backward Compatibility

---

projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts
projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts
projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts
projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html
projects/dsp-ui/src/lib/search/search-panel/search-panel.component.spec.ts
projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
src/app/search-playground/search-playground.component.html

resolves DSP-1132
In this PR I added `limitToProject` parameter to advanced search. It can be used in project specific apps to list project specific ontologies only.
`limitToProject` can be used in advanced-search, in fulltext-search and in search-panel which is a combination of advanced- and fulltext-search. ~~But at the moment I have an issue with communication between the three components.~~
~~In case of `projectFilter = true` it shows a dropdown menu as part of fulltext-search to select a project. When I select a project it emits the data from fulltext-search to parent, in this case `search-panel`. limitToProject is a two-way-binding object of fulltext-search. But it ends in an `ExpressionChangedAfterItHasBeenCheckedError` in case a project is already selected when page refreshs …

DSP-1132 Advanced search limit to project

---

.github/workflows/main.yml
CHANGELOG.md
package-lock.json
package.json
projects/dsp-ui/package.json
vars.mk

To run [release-please-action](https://github.com/marketplace/actions/release-please-action) (from PR #243) the correct way, we have to do a real release first. Otherwise the mentioned action script will not work properly with all the release candidates.
In this PR I updated DSP-JS to latest version 1.0.0 (which works fine with DSP-API 13.0.0-rc.25) and I fixed some dependency security issues.

Prepare release 1.0.0

---

projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts

Fix Value Form Control Name

---

projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.ts
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts

fix(Date Value Validators): Propagate valueRequiredValidator to child component (DSP-1188)

---

projects/dsp-ui/src/lib/viewer/values/date-value/date-input/date-input.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/interval-value/interval-input/interval-input.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.html
projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/time-value/time-input/time-input.component.ts
projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html
projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts

fix(Time Value Validators): Propagate valueRequiredValidator to child component (DSP-1218)

---

projects/dsp-ui/package.json
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/value.service.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts

refactor: update constants (DSP-1187)

---

projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.spec.ts
projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.ts

feat(string-literal-input): updates input on label changes (DSP-1295)

---

projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-edit/date-edit.component.scss
projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.html
projects/dsp-ui/src/lib/viewer/values/date-value/date-input-text/date-input-text.component.scss

feat(viewer): improve style of date input (DSP-1724)

---

projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.spec.ts
projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.ts

feat(action): only show era if supported by calendar (DSP-1725)

---

projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html
projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts

feat(viewer): make hex code display optional for color value (DSP-1667)

---

projects/dsp-ui/src/lib/viewer/services/geoname.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/geoname.service.ts
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts
src/app/viewer-playground/viewer-playground.component.spec.ts
src/config/config.dev.json
src/config/config.prod.json

resolves DSP-1212
This PR adds a service that resolves a geoname id.
@gautschr @kilchenmann I'd like to discuss whether and to what degree we could also implement the autocomplete functionality for creating / editing values (like in DSP-Tangoh). As for the backend, we decided not to reimplement the logic with hierarchical lists as it was implemented in SALSAH.

feat(viewer): resolve geoname id and show name (DSP-1212)

---

projects/dsp-ui/src/lib/viewer/services/geoname.service.spec.ts
projects/dsp-ui/src/lib/viewer/services/geoname.service.ts
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.scss
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts
projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts

feat(viewer): improve editing of geonames (DSP-1212)

---

projects/dsp-ui/src/lib/action/action.module.ts
projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.html
projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.scss
projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.spec.ts
projects/dsp-ui/src/lib/action/components/selected-resources/selected-resources.component.ts
projects/dsp-ui/src/lib/action/index.ts
src/app/action-playground/action-playground.component.html
src/app/action-playground/action-playground.component.ts

resolves DSP-1765
It is the intermediate page displayed when user selects multiple resources using checkboxes in resource-list or grid. 
It displays:
- number of resources selected
- ids of the selected resources
- list of actions applied to the selected resources
At the moment, it contains very simple design to complete the functionality of the comparison viewer. The style will be modified later as shown in the Figma.

feat(action): intermediate page for selected resources in comparison viewer (DSP-1765)

---

package.json
projects/dsp-ui/src/lib/viewer/index.ts
projects/dsp-ui/src/lib/viewer/viewer.module.ts
projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.html
projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.scss
projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.ts
src/app/viewer-playground/viewer-playground.component.html
src/app/viewer-playground/viewer-playground.component.ts

resolves DSP-1785
In this PR, we are splitting pane to show multiple resources selected for comparison.
Note: Every resource displayed on the page has its own slider and in result there are multiple sliders present on the page. It makes the navigation difficult on the page. Does anyone have any idea how we can simplify it?

feat(viewer): split pane to compare multiple resource (DSP-1785)

---

package-lock.json
projects/dsp-ui/package.json
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.service.spec.ts
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.service.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts

refactor(resource): clean up code and refactoring (DSP-1816)

---

projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts

resolves DSP-1575
It's all described here: <https://dasch.myjetbrains.com/youtrack/issue/DSP-1575#focus=Comments-4-3308.0-0>

fix(viewer): fix several issues in list-view (DSP-1575)

---

projects/dsp-ui/src/lib/action/pipes/string-transformation/linkify.pipe.spec.ts
projects/dsp-ui/src/lib/action/pipes/string-transformation/linkify.pipe.ts

fix(action): bug fix in linkify pipe (DSP-1837)

---

.gitignore
projects/dsp-ui/ng-package.json
projects/dsp-ui/package.json
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
projects/dsp-ui/src/lib/viewer/views/list-view/list-view.service.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html
projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts
projects/dsp-ui/src/lib/viewer/views/multiple-resources-view/multiple-resources-view.component.ts
src/app/viewer-playground/viewer-playground.component.html
src/app/viewer-playground/viewer-playground.component.ts

resolves DSP-1842 (Expand the "FilteredResources" by label)
and refactor the multiple selection bug DSP-1820 (in detail: <https://dasch.myjetbrains.com/youtrack/issue/DSP-1820#focus=Comments-4-3346.0-0>)

refactor(viewer): return label and id in multiple resource selection (DSP-1842 / DSP-1820)

---

package-lock.json
projects/dsp-ui/src/assets/style/_viewer.scss
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts
projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.ts
src/app/modify/modify.component.ts

feat(display-edit): disable delete depending on cardinality (DSP-1814)
