dasch-swiss/dsp-ui-lib

projects/knora-ui/src/lib/viewer/values/custom-regex.ts, projects/knora-ui/src/lib/viewer/values/custom-validators.ts, projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts
=> feature (value): moved custom regex validators to a shared class

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html, projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts, projects/knora-ui/src/lib/viewer/viewer.module.ts
=> Decimal Value Component

projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/time-value/jdn-datepicker-directive/jdndatepicker.directive.spec.ts
=> fix (linkValue) fixes the failing test

projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.html, projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.html, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-html/text-value-as-html.component.ts, projects/knora-ui/src/lib/viewer/viewer.module.ts, src/app/app.component.ts
=> Text Value as Html

.github/workflows/nodejs.yml, README.md, angular.json, package.json, projects/knora-ui/README.md, projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts, projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts, projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts, src/config/config.prod.json, src/environments/environment.prod.ts
This PR implements https://dasch.myjetbrains.com/youtrack/issue/DSP-104
=> Simulate productive circumstances locally

.github/workflows/nodejs.yml, package-lock.json, package.json, projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts, projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.component.spec.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/modify/modify.component.html, src/app/modify/modify.component.spec.ts, src/app/modify/modify.component.ts, src/app/read/read.component.html, src/app/read/read.component.spec.ts, src/app/read/read.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-179
=> Improve app playground with routes

package.json, src/app/modify/modify.component.ts, src/app/read/read.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-192
=> Playground code clean up and package.json test addition

package-lock.json
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-194
=> BUG: User can no longer save an edited value

projects/knora-ui/src/lib/viewer/values/base-value.component.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts, projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts
https://dasch.myjetbrains.com/youtrack/issue/DSP-188
https://dasch.myjetbrains.com/youtrack/issue/DSP-187
=> Create Value Comparison Method

projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html, projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts, projects/knora-ui/src/lib/viewer/values/color-value/color-picker/color-picker.component.html, projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.html, projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts, projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html, projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts, projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.html, projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.ts, projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.html, projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts, projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.html, projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.ts, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts, projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.html, projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.ts, projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.html, projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-131
=> cdkTextareaAutosize code cleanup

projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.spec.ts, projects/knora-ui/src/lib/viewer/pipes/knoradate.pipe.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-217
=> FIX: KnoraDatePipe return values

.github/workflows/nodejs.yml, package-lock.json, package.json, projects/knora-ui/package.json, projects/knora-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/knora-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/link-value/link-value.component.ts, projects/knora-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts, projects/knora-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts, projects/knora-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts, projects/knora-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts, projects/knora-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts, yalc.lock
Use @knora/api 1.0.0-rc.0. 
No local build of `@knora/api 1.0.0-rc.0` required anymore!
=> Use @knora/api 1.0.0-rc.0

projects/dsp-ui/package.json
https://dasch.myjetbrains.com/youtrack/issue/DSP-233
=> Add ngx-color-picker to lib's peer deps

CHANGELOG.md, README.md, projects/dsp-ui/package.json
Closes https://dasch.myjetbrains.com/youtrack/issue/DSP-241
In this PR:
- Changelog from release notes
- Correct badges with links in main Readme
- Lib package.json with additional infos for npm (License, Keywords)
=> Update package information

projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.spec.ts, projects/dsp-ui/src/lib/action/pipes/string-transformation/truncate.pipe.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-276
=> Refactor Truncate Pipe

tslint.json
Resolves [DSP-300](https://dasch.myjetbrains.com/youtrack/issue/DSP-300)
=> Update tslint 

projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts
relates to https://dasch.myjetbrains.com/youtrack/issue/DSP-140
=> Int Value Comp Specs: Using MatHarness

projects/dsp-ui/src/lib/action/action.module.ts, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.html, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.scss, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.spec.ts, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts, projects/dsp-ui/src/lib/action/index.ts, src/app/action-playground/action-playground.component.html, src/app/action-playground/action-playground.component.spec.ts, src/app/action-playground/action-playground.component.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.scss, src/app/app.module.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-320
=> Migrate sort button

projects/dsp-ui/src/lib/action/action.module.ts, projects/dsp-ui/src/lib/action/components/message/message.component.html, projects/dsp-ui/src/lib/action/components/message/message.component.scss, projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts, projects/dsp-ui/src/lib/action/components/message/message.component.ts, projects/dsp-ui/src/lib/action/index.ts, projects/dsp-ui/src/lib/assets/i18n/statusMsg.ts, projects/dsp-ui/src/lib/assets/style/_responsive.scss, src/app/action-playground/action-playground.component.html, src/app/action-playground/action-playground.component.spec.ts, src/app/action-playground/action-playground.component.ts, src/app/modify/modify.component.html, src/app/modify/modify.component.spec.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-327
=> Migration of message component

projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-391
=> FIX: Sort button type annotation

projects/dsp-ui/src/lib/action/services/sorting.service.spec.ts, projects/dsp-ui/src/lib/action/services/sorting.service.ts, src/app/action-playground/action-playground.component.ts
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-415
=> Make the sorting service more flexible

package-lock.json, package.json, projects/dsp-ui/package.json
This PR updates the JS-Lib dep. to rc.4.
=> Update JS-Lib Dep

README.md, package.json
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-439
=> DSP-UI Live Reloading

projects/dsp-ui/src/lib/viewer/viewer.module.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.scss, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
closes [DSP-441](https://dasch.myjetbrains.com/youtrack/issue/DSP-441)
=> Add ArkUrl copy to clipboard in resource-view

projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts, projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
closes [DSP-443](https://dasch.myjetbrains.com/youtrack/issue/DSP-443)
=> Fix tests to remove error messages in the console

projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html
closes [DSP-453](https://dasch.myjetbrains.com/youtrack/issue/DSP-453)
=> Hide link to geonames.org in edit mode

projects/dsp-ui/src/lib/action/action.module.ts, projects/dsp-ui/src/lib/action/index.ts, projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.spec.ts, projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.ts, src/app/action-playground/action-playground.component.html, src/app/action-playground/action-playground.component.ts, src/app/app.component.scss
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-504
=> Migrate Stringify String Literal Pipe

projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.scss
Resolves [DSP-520](https://dasch.myjetbrains.com/youtrack/issue/DSP-520)
=> Optimise the number of cards per line

projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts
https://dasch.myjetbrains.com/youtrack/issue/DSP-521
=> Warning When Running Lib's Tests

projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.html
resolves [DSP-518](https://dasch.myjetbrains.com/youtrack/issue/DSP-518)
=> Change Home Icon of OpenSeadragon Viewer

projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-523
=> FIX: DSP UI is blocked when submitting an invalid value

CHANGELOG.md, README.md, projects/dsp-ui/README.md
- Update the CHANGELOG with the notes of v1.0.0-rc.2 (add the notes to the doc as an history)
- Add more details about the publication of releases in the main README
- Edit the license badge link in the main README and the dsp-ui README
=> Update CHANGELOG and READMEs

projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/operator.ts, projects/dsp-ui/src/lib/search/index.ts
resolves [DSP-530](https://dasch.myjetbrains.com/youtrack/issue/DSP-530)
=> Export operator.ts

projects/dsp-ui/package.json
I forgot to update the version of dsp-js-lib in module's package.json
=> Update dsp-js-lib to version 1.0.0-rc.6

projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html, projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html, projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-488
uses DSP-API v13.0.0-rc.11
=> Error handling: submitting duplicate values

package-lock.json, projects/dsp-ui/package.json, projects/dsp-ui/src/assets/style/_viewer.scss, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-529
uses js-lib v1.0.0-rc.9 and dsp-api v13.0.0-rc.12
=> Make URI values clickable

projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-528
uses dsp-js v1.0.0-rc-7 and dsp-api rc-12
=> Emit link value when clicked on

projects/dsp-ui/src/lib/action/action.module.ts, projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.spec.ts, projects/dsp-ui/src/lib/action/directives/gnd/gnd.directive.ts, src/app/action-playground/action-playground.component.html
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-579
=> Export GND directive

projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-584
=> Anchor Tag in Link Value's HTML

projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-585
=> dsp-property-toolbar warnings in unit tests

projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.spec.ts, projects/dsp-ui/src/lib/action/pipes/formatting/knoradate.pipe.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.html, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-568
uses uses js-lib v1.0.0-rc.9 and dsp-api v13.0.0-rc.12
=> Read mode date value era and calendar

package-lock.json, package.json, projects/dsp-ui/package.json
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-592
=> Update peer-dep for dsp-js lib

projects/dsp-ui/src/lib/action/components/message/message.component.spec.ts, projects/dsp-ui/src/lib/action/components/message/message.component.ts, src/app/action-playground/action-playground.component.html, src/app/action-playground/action-playground.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-595
uses knora-api rc.12 and js-lib rc.9
=> Message component timer

projects/dsp-ui/src/lib/search/search-panel/search-panel.component.html, projects/dsp-ui/src/lib/search/search-panel/search-panel.component.scss, projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
closes [DSP-590](https://dasch.myjetbrains.com/youtrack/issue/DSP-590)
=> Search Panel: Advanced Search Not Displayed

projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html
closes [DSP-606](https://dasch.myjetbrains.com/youtrack/issue/DSP-606)
=> Rephrase "This source belongs to project" in the resource viewer

projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-588
I figured that I can use the ternary operator in the template which simplifies the logic quite a bit.
The following sources suggest that approach:
- https://angular.io/guide/template-expression-operators#the-pipe-operator- (see blue box)
- https://angular.io/api/common/NgIf#showing-an-alternative-template-using-else (see template)
=> Show label for URI Value (if set)

projects/dsp-ui/src/lib/action/action.module.ts, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.html, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.scss, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.ts, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.html, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.scss, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.spec.ts, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.ts, projects/dsp-ui/src/lib/action/index.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.ts, src/app/action-playground/action-playground.component.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-613
uses js-lib rc.10 and dsp-api rc.14
=> Confirmation Dialog Message Subcomponent

projects/dsp-ui/src/lib/viewer/services/value-type.service.spec.ts, projects/dsp-ui/src/lib/viewer/services/value-type.service.ts
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-630
=> Fix compareObjectTypeWithValueType Method

package-lock.json, package.json, projects/dsp-ui/package.json
We have to publish new release candidate because of a mistake in my previous release.
=> Prerelease 1.0.0-rc.7

projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html
closes https://dasch.myjetbrains.com/youtrack/issue/DSP-644
uses js-lib rc.11 and dsp-api rc.15
=> Date & Interval Components: Remove Parent Input Placeholder

projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.html, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.scss, projects/dsp-ui/src/lib/action/components/sort-button/sort-button.component.ts, src/app/action-playground/action-playground.component.html
resolves [DSP-693](https://dasch.myjetbrains.com/youtrack/issue/DSP-693)
=> DSP-693 Sort button style

.github/workflows/main.yml, Makefile
resolves [DSP-436](https://dasch.myjetbrains.com/youtrack/issue/DSP-436)
=> DSP-436 Fix workflow issue 

.github/pull_request_template.md
resolves [DSP-701](https://dasch.myjetbrains.com/youtrack/issue/DSP-701)
=> DSP-701 Add template for PRs

.github/workflows/main.yml
resolves [DSP-708](https://dasch.myjetbrains.com/youtrack/issue/DSP-708)
In this PR I just cleaned up the CI workflow config by removing a redundant step in publish process.
=> DSP-708 Refactor CI workflow script

projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts
resolves [DSP-674](https://dasch.myjetbrains.com/youtrack/issue/DSP-674)
=> DSP-674 Bug fix in search panel

projects/dsp-ui/src/lib/viewer/index.ts, projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.ts, projects/dsp-ui/src/lib/viewer/services/value-type.service.ts, projects/dsp-ui/src/lib/viewer/values/base-value.component.ts, projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts, projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts, projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts, projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts, projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts, projects/dsp-ui/src/lib/viewer/viewer.module.ts
resolves [DSP-881](https://dasch.myjetbrains.com/youtrack/issue/DSP-881)
=> DSP-881 - Value Component Base Class Changes

.github/pull_request_template.md, .github/workflows/main.yml, CHANGELOG.md, README.md, projects/dsp-ui/README.md
resolves DSP-920 and as preparation for next release: Update CHANGELOG
=> DSP-920 Renaming default github branch to "main"

README.md
=> Explain Demo App (Playground)

projects/dsp-ui/src/lib/action/components/login-form/login-form.component.spec.ts, projects/dsp-ui/src/lib/action/components/login-form/login-form.component.ts, projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.spec.ts, projects/dsp-ui/src/lib/action/components/string-literal-input/string-literal-input.component.ts, projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.spec.ts, projects/dsp-ui/src/lib/action/pipes/string-transformation/stringify-string-literal.pipe.ts, projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.spec.ts, projects/dsp-ui/src/lib/search/advanced-search/advanced-search.component.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/select-property.component.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.spec.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.spec.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-link-value/search-link-value.component.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.spec.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-list-value/search-list-value.component.ts, projects/dsp-ui/src/lib/search/expert-search/expert-search.component.spec.ts, projects/dsp-ui/src/lib/search/expert-search/expert-search.component.ts, projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.spec.ts, projects/dsp-ui/src/lib/search/fulltext-search/fulltext-search.component.ts, projects/dsp-ui/src/lib/search/search-panel/search-panel.component.ts, projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts, projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
=> DSP-924 Never Import from index.ts Internally

projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.html, projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.scss, src/app/viewer-playground/viewer-playground.component.ts
=> DSP-768 Styling issue in resource (properties) viewer

projects/dsp-ui/src/lib/search/expert-search/expert-search.component.ts, projects/dsp-ui/src/lib/viewer/representation/still-image/still-image.component.scss, projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts, src/app/viewer-playground/viewer-playground.component.ts
=> DSP-1028 Activate still-image in resource viewer

projects/dsp-ui/src/lib/action/services/notification.service.ts
=> DSP-1075 Bug in notification service

Makefile
=> Adapt knora-api repo name

package-lock.json, package.json, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-dialog.component.spec.ts, projects/dsp-ui/src/lib/action/components/confirmation-dialog/confirmation-message/confirmation-message.component.spec.ts, projects/dsp-ui/src/lib/viewer/operations/add-value/add-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts, projects/dsp-ui/src/lib/viewer/services/value.service.spec.ts, projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/property-view/property-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts, src/app/still-image/still-image-playground.component.spec.ts, src/app/viewer-playground/viewer-playground.component.spec.ts
=> DSP-1097 - Bump JS-Lib Version and Fix Breaking Changes

package-lock.json, package.json, projects/dsp-ui/package.json, vars.mk
- Update DSP-API to v13.0.0-rc.23
- Update DSP-JS-Lib to v1.0.0-rc.17
=> Update DSP dependencies

projects/dsp-ui/src/assets/style/_viewer.scss, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.html, projects/dsp-ui/src/lib/viewer/views/list-view/resource-grid/resource-grid.component.ts, projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.html, projects/dsp-ui/src/lib/viewer/views/list-view/resource-list/resource-list.component.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts
resolves DSP-945
It updates the resource viewer.
* enhancement (resource-grid-viewer): highlight selected item from grid, by default select first item.
* enhancement (resource-list-viewer): highlight selected item from list, by default select first item.
=> DSP-945-update resource viewer

projects/dsp-ui/src/assets/style/_viewer.scss, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.scss, projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.html, projects/dsp-ui/src/lib/viewer/views/property-view/property-toolbar/property-toolbar.component.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.html, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.ts, src/app/viewer-playground/viewer-playground.component.html, src/app/viewer-playground/viewer-playground.component.scss, src/app/viewer-playground/viewer-playground.component.ts
resolves DSP-1112, DSP-1023 and part of DSP-1110
=> DSP-1110 Bug fixes and styling improvement in resource viewer

projects/dsp-ui/src/lib/viewer/representation/upload-file/upload-file.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.spec.ts, projects/dsp-ui/src/lib/viewer/views/resource-view/resource-view.component.spec.ts
=> Fix Warnings And Remove Log Messages in Specs

README.md, projects/dsp-ui/Contribution.md, projects/dsp-ui/README.md
=> Improve README

projects/dsp-ui/design-documentation.md, projects/dsp-ui/src/lib/viewer/values/base-value.component.ts, projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.html, projects/dsp-ui/src/lib/viewer/values/boolean-value/boolean-value.component.ts, projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.html, projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.ts, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.html, projects/dsp-ui/src/lib/viewer/values/date-value/date-value.component.ts, projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.html, projects/dsp-ui/src/lib/viewer/values/decimal-value/decimal-value.component.ts, projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.html, projects/dsp-ui/src/lib/viewer/values/geoname-value/geoname-value.component.ts, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.html, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/int-value/int-value.component.ts, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.html, projects/dsp-ui/src/lib/viewer/values/interval-value/interval-value.component.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.html, projects/dsp-ui/src/lib/viewer/values/list-value/list-value.component.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.html, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-string/text-value-as-string.component.ts, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.html, projects/dsp-ui/src/lib/viewer/values/text-value/text-value-as-xml/text-value-as-xml.component.ts, projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.html, projects/dsp-ui/src/lib/viewer/values/time-value/time-value.component.ts, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.html, projects/dsp-ui/src/lib/viewer/values/uri-value/uri-value.component.ts
=> DSP-1175 - Change Required Validator for Value Components to be Optional

.github/workflows/main.yml
- Set correct package name and path in release-please-action
- New feature in CI: Send notification to google chat
=> chore(CI): Update workflow

package-lock.json, package.json, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/operator-constants.ts, projects/dsp-ui/src/lib/search/advanced-search/select-property/specify-property-value/search-date-value/search-date-value.component.ts, projects/dsp-ui/src/lib/viewer/operations/display-edit/display-edit.component.spec.ts
- Update to latest version of DSP-JS v1.0.1
- Rename all `Constants.Delimiter` to `Constants.HashDelimiter`
=> Update js-lib version to v1.0.1

projects/dsp-ui/package.json
=> chore: update dsp-js version

.github/pull_request_template.md
=> chore: update pr template (DSP-1189)

.github/workflows/main.yml
=> chore(gh-ci): Update release-please

package-lock.json, package.json
=> chore: update JS-Lib version to 1.1.0

projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.html, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.spec.ts, projects/dsp-ui/src/lib/viewer/values/link-value/link-value.component.ts
=> fix(Link Value): custom validator should allow null (DSP-1237)

package-lock.json, package.json, projects/dsp-ui/package.json
=> chore(package.json): update dsp-js

e2e/src/app.e2e-spec.ts
This PR attempts to improve stability of e2e tests.
=> test(e2e):  improve stability of e2e tests.

package-lock.json, package.json, projects/dsp-ui/package.json, vars.mk
=> chore: update dsp-js version to 1.2.1

package-lock.json, package.json, projects/dsp-ui/package.json, vars.mk
=> chore: update DSP-JS to version 1.3.0

package-lock.json, package.json, projects/dsp-ui/package.json, vars.mk
=> chore (dependency): update dsp-js to 2.0.1 and dsp-api to 13.3.1

.github/workflows/main.yml
=> chore(gh-ci): update release please configuration (DSP-1380)

package.json
Alibi PR to trigger release PR.
=> chore(package.json): improve description

package.json
=> chore(package.json): improve description (DSP-1468)

projects/dsp-ui/package.json
=> chore(package.json): improve description in package.json (DSP-1468)

projects/dsp-ui/src/lib/viewer/values/color-value/color-value.component.scss
=> fix(viewer): set correct rgba value (DSP-1588)

projects/dsp-ui/src/lib/viewer/index.ts
=> chore(viewer): export value operation events (DSP-1590)

projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.html, projects/dsp-ui/src/lib/viewer/views/list-view/list-view.component.ts
=> feat(list-view): Create boolean flag to enable/disable the view switcher (DSP-1597)

.github/workflows/main.yml
=> chore(github actions): replace token

docs/how-to-contribute/design-documentation.md, docs/how-to-use/getting-started.md
=> docs(improve docs): add some missing parts (DSP-1752)
